run:
  timeout: 15m0s
  skip-dirs-use-default: true
  fast: false
#  modules-download-mode: readonly

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - "k8s.io/apimachinery"
          - "k8s.io/api"
          - "k8s.io/kubectl/pkg/drain"
          - "k8s.io/kubelet"
          - "k8s.io/utils"
          - "k8s.io/client-go"
          - "github.com/onsi/ginkgo"
          - "github.com/openshift"
          - "github.com/nmstate/kubernetes-nmstate"
          - "github.com/k8snetworkplumbingwg"
          - "github.com/metallb/metallb-operator"
          - "github.com/metal3-io/baremetal-operator"
          - "github.com/operator-framework/operator-lifecycle-manager"
          - "github.com/grafana-operator/grafana-operator"
          - "github.com/NVIDIA/gpu-operator/"
          - "github.com/operator-framework/api"
          - "github.com/argoproj-labs/argocd-operator/api"
          - "github.com/golang/glog"
          - "github.com/rh-ecosystem-edge/kernel-module-management/"
          - "maistra.io/api/"
          - "open-cluster-management.io/governance-policy-propagator/api"
          - "open-cluster-management.io/governance-policy-propagator/api/v1beta1"
          - "open-cluster-management.io/multicloud-operators-subscription/pkg/apis/apps/placementrule/v1"
          - "open-cluster-management.io/api"
          - "sigs.k8s.io/controller-runtime"
          - "github.com/stretchr/testify"
          - $gostd
          - "github.com/stretchr/testify"
          - "github.com/vmware-tanzu/velero"
          - "github.com/kelseyhightower/envconfig"
          - "github.com/red-hat-storage/ocs-operator"
          - "github.com/stmcginnis/gofish"
          - "github.com/stolostron/backplane-operator/api/v1"
  revive:
    rules:
      - name: indent-error-flow
      - name: var-naming
      - name: increment-decrement
      - name: exported
        arguments:
          - disableStutteringCheck
  wsl:
    strict-append: false
  gofmt:
    simplify: true
  funlen:
    lines: 90
    statements: 40
  unused:
    check-exported: true
    go: "1.22"
  stylecheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.22"
    # https://staticcheck.io/docs/options#checks
    checks:
      - all
      - ST1001

linters:
  disable:
    - structcheck
  enable:
    - asciicheck
    - bidichk
    - depguard
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - importas
    - ineffassign
    - ireturn
    - lll
    - makezero
    - misspell
    - nakedret
    - nilnil
    - nolintlint
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - stylecheck
    - tenv
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - varnamelen
    - wsl
    - nlreturn

output:
  format: colored-line-number
issues:
  include:
    - EXC0002 # disable excluding of issues about comments from golint
    - EXC0012  # EXC0012 revive: Annoying issue about not having a comment. The rare codebase has such comments
    - EXC0014  # EXC0014 revive: Annoying issue about not having a comment. The rare codebase has such comments
  exclude-rules:
    #- # Exclude some linters from running on tests files.
    - path: 'pkg/polarion'
      linters:
        - exhaustive



