run:
  timeout: 15m0s
  skip-dirs-use-default: true
  fast: false
#  modules-download-mode: readonly

linters-settings:
  revive:
    rules:
      - name: indent-error-flow
      - name: var-naming
      - name: increment-decrement
      - name: exported
        arguments:
          - disableStutteringCheck
  wsl:
    strict-append: false
  gofmt:
    simplify: true
  funlen:
    lines: 90
    statements: 40
  unused:
    check-exported: true
    go: "1.19"
  stylecheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.19"
    # https://staticcheck.io/docs/options#checks
    checks:
      - all
      - ST1001

linters:
  disable:
    - structcheck
  enable:
    - asciicheck
    - bidichk
    - depguard
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - importas
    - ineffassign
    - ireturn
    - lll
    - makezero
    - misspell
    - nakedret
    - nilnil
    - nolintlint
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - stylecheck
    - tenv
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - varnamelen
    - wsl
    - nlreturn

output:
  format: colored-line-number
issues:
  exclude:
    - "can't run linter goanalysis_metalinter: inspect: failed to load"
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  include:
    - EXC0002 # disable excluding of issues about comments from golint
    - EXC0012  # EXC0012 revive: Annoying issue about not having a comment. The rare codebase has such comments
    - EXC0014  # EXC0014 revive: Annoying issue about not having a comment. The rare codebase has such comments
  exclude-rules:
    #- # Exclude some linters from running on tests files.
    - path: 'tests/internal/inittools'
      linters:
        - gochecknoinits
    - path: 'tests/cnf/core/network/internal/netinittools'
      linters:
        - gochecknoinits
    - path: 'tests/assisted/ztp/internal/ztpinittools'
      linters:
        - gochecknoinits
    - path: 'tests/internal/polarion'
      linters:
        - exhaustive

    - path: 'tests/internal/polarion'
      linters:
        - depguard

    - path: 'tests/internal/reporter'
      linters:
        - depguard

    - path: "tests/.*/tests/.*"
      linters:
        - depguard

    - path: "tests/.*/.*suite_test.go"
      linters:
        - depguard
