// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package common

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AlarmDefinitionAlarmChangeType.
const (
	ADDED    AlarmDefinitionAlarmChangeType = "ADDED"
	DELETED  AlarmDefinitionAlarmChangeType = "DELETED"
	MODIFIED AlarmDefinitionAlarmChangeType = "MODIFIED"
)

// Defines values for AlarmDefinitionClearingType.
const (
	AUTOMATIC AlarmDefinitionClearingType = "AUTOMATIC"
	MANUAL    AlarmDefinitionClearingType = "MANUAL"
)

// Defines values for AlarmDefinitionManagementInterfaceId.
const (
	AlarmDefinitionManagementInterfaceIdO2IMS AlarmDefinitionManagementInterfaceId = "O2IMS"
)

// Defines values for AlarmDictionaryManagementInterfaceId.
const (
	AlarmDictionaryManagementInterfaceIdO2IMS AlarmDictionaryManagementInterfaceId = "O2IMS"
)

// APIVersion Information about a version of the API.
type APIVersion struct {
	Version *string `json:"version,omitempty"`
}

// APIVersions Information about a list of versions of the API.
type APIVersions struct {
	ApiVersions *[]APIVersion `json:"apiVersions,omitempty"`
	UriPrefix   *string       `json:"uriPrefix,omitempty"`
}

// AlarmDefinition Information about an alarm definition.
type AlarmDefinition struct {
	// AlarmAdditionalFields List of metadata key-value pairs used to associate meaningful metadata to the related resource type.
	AlarmAdditionalFields *map[string]interface{} `json:"alarmAdditionalFields,omitempty"`

	// AlarmChangeType Indicates the type of change that occurred during the alarm last change; added, deleted, modified.
	AlarmChangeType AlarmDefinitionAlarmChangeType `json:"alarmChangeType"`

	// AlarmDefinitionId Provides a unique identifier of the alarm being raised. This is the Primary Key into the Alarm Dictionary
	AlarmDefinitionId openapi_types.UUID `json:"alarmDefinitionId"`

	// AlarmDescription Provides a longer descriptive meaning of the alarm condition and a description of the consequences of the
	// alarm condition. This is intended to be read by an operator to give an idea of what happened and a sense of
	// the effects, consequences, and other impacted areas of the system.
	AlarmDescription string `json:"alarmDescription"`

	// AlarmLastChange Indicates the Alarm Dictionary Version in which this alarm last changed.
	AlarmLastChange string `json:"alarmLastChange"`

	// AlarmName Provides short name for the alarm
	AlarmName string `json:"alarmName"`

	// ClearingType Identifies whether alarm is cleared automatically or manually.
	ClearingType AlarmDefinitionClearingType `json:"clearingType"`

	// ManagementInterfaceId List of management interface over which alarms are transmitted for this Entity Type.
	// RESTRICTION: For the O-Cloud IMS Services this value is limited to O2IMS.
	ManagementInterfaceId []AlarmDefinitionManagementInterfaceId `json:"managementInterfaceId"`

	// PkNotificationField Identifies which field or list of fields in the alarm notification contains the primary key (PK) into the
	// Alarm Dictionary for this interface; i.e. which field contains the Alarm Definition ID.
	PkNotificationField []string `json:"pkNotificationField"`

	// ProposedRepairActions Provides guidance for proposed repair actions.
	ProposedRepairActions string `json:"proposedRepairActions"`
}

// AlarmDefinitionAlarmChangeType Indicates the type of change that occurred during the alarm last change; added, deleted, modified.
type AlarmDefinitionAlarmChangeType string

// AlarmDefinitionClearingType Identifies whether alarm is cleared automatically or manually.
type AlarmDefinitionClearingType string

// AlarmDefinitionManagementInterfaceId defines model for AlarmDefinition.ManagementInterfaceId.
type AlarmDefinitionManagementInterfaceId string

// AlarmDictionary Information about an alarm dictionary.
type AlarmDictionary struct {
	AlarmDefinition []AlarmDefinition `json:"alarmDefinition"`

	// AlarmDictionaryId The Identifier of the Alarm Dictionary. The Identifier is unique within an O-Cloud.
	AlarmDictionaryId openapi_types.UUID `json:"alarmDictionaryId"`

	// AlarmDictionarySchemaVersion Version of the Alarm Dictionary Schema to which this alarm dictionary conforms.
	AlarmDictionarySchemaVersion string `json:"alarmDictionarySchemaVersion"`

	// AlarmDictionaryVersion Version of the Alarm Dictionary. Version is vendor defined such that the version of the dictionary can be
	// associated with a specific version of the software delivery of this product.
	AlarmDictionaryVersion string `json:"alarmDictionaryVersion"`

	// EntityType O-RAN entity type emitting the alarm: This shall be unique per vendor ResourceType.model and
	// ResourceType.version
	EntityType string `json:"entityType"`

	// ManagementInterfaceId List of management interface over which alarms are transmitted for this Entity Type.
	// RESTRICTION: For the O-Cloud IMS Services this value is limited to O2IMS.
	ManagementInterfaceId []AlarmDictionaryManagementInterfaceId `json:"managementInterfaceId"`

	// PkNotificationField Identifies which field or list of fields in the alarm notification contains the primary key (PK) into the
	// Alarm Dictionary for this interface; i.e. which field contains the Alarm Definition ID.
	PkNotificationField []string `json:"pkNotificationField"`

	// Vendor Vendor of the Entity Type to whom this Alarm Dictionary applies. This should be the same value as in the
	// ResourceType.vendor attribute
	Vendor string `json:"vendor"`
}

// AlarmDictionaryManagementInterfaceId defines model for AlarmDictionary.ManagementInterfaceId.
type AlarmDictionaryManagementInterfaceId string

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	// AdditionalAttributes Any number of additional attributes, as defined in a specification or by an implementation.
	AdditionalAttributes *map[string]string `json:"additionalAttributes,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	// It may yield further information if dereferenced.
	Instance *string `json:"instance,omitempty"`

	// Status The HTTP status code for this occurrence of the problem.
	Status int `json:"status"`

	// Title A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem,
	// except for purposes of localization. If type is given and other than "about:blank", this attribute shall also be provided.
	Title *string `json:"title,omitempty"`

	// Type A URI reference according to IETF RFC 3986 [3] that identifies the problem type. It is encouraged that the URI provides
	// human-readable documentation for the problem (e.g. usingHTML) when dereferenced. When this member is not present,
	// its value is assumed to be "about:blank".
	Type *string `json:"type,omitempty"`
}

// AlarmDictionaryId defines model for alarmDictionaryId.
type AlarmDictionaryId = openapi_types.UUID

// AllFields defines model for allFields.
type AllFields = string

// ExcludeFields defines model for excludeFields.
type ExcludeFields = string

// Fields defines model for fields.
type Fields = string

// Filter defines model for filter.
type Filter = string
