---
- name: nvidiagpu
  sync: true
  repo_link: "https://github.com/NVIDIA/gpu-operator"
  branch: main
  remote_api_directory: api/nvidia/v1
  local_api_directory: schemes/nvidiagpu/nvidiagputypes
  replace_imports:
    - old: '"github.com/NVIDIA/k8s-kata-manager/api/v1alpha1/config"'
      new: '"github.com/rh-ecosystem-edge/eco-goinfra/pkg/schemes/nvidiagpu/k8skatamanager/v1alpha1/config"'
    - old: '"github.com/NVIDIA/k8s-operator-libs/api/upgrade/v1alpha1"'
      new: '"github.com/rh-ecosystem-edge/eco-goinfra/pkg/schemes/nvidiagpu/k8skoperatorlibs/upgrade/v1alpha1"'
    - old: '"github.com/NVIDIA/gpu-operator/internal/consts"'
      new: '"github.com/rh-ecosystem-edge/eco-goinfra/pkg/schemes/nvidiagpu/nvidiagputypes/internal/consts"'
    - old: '"golang.org/x/mod/semver"'
      new: '"github.com/rh-ecosystem-edge/eco-goinfra/pkg/schemes/nvidiagpu/semver"'

- name: nvidiagpu
  sync: true
  repo_link: "https://github.com/NVIDIA/gpu-operator"
  branch: main
  remote_api_directory: internal/consts
  local_api_directory: schemes/nvidiagpu/nvidiagputypes/internal/consts

- name: semver
  sync: true
  repo_link: "https://go.googlesource.com/mod"
  branch: master
  remote_api_directory: semver
  local_api_directory: schemes/nvidiagpu/semver
  excludes:
    - "*_test.go"

- name: k8s-kata-manager
  sync: true
  repo_link: "https://github.com/NVIDIA/k8s-kata-manager"
  branch: main
  remote_api_directory: api/v1alpha1
  local_api_directory: schemes/nvidiagpu/k8skatamanager/v1alpha1
  excludes:
    - "*_test.go"

- name: k8s-operator-libs
  sync: true
  repo_link: "https://github.com/NVIDIA/k8s-operator-libs"
  branch: main
  remote_api_directory: api/upgrade/v1alpha1
  local_api_directory: schemes/nvidiagpu/k8skoperatorlibs/upgrade/v1alpha1
...