---
- name: olm-operators
  sync: true
  repo_link: "https://github.com/operator-framework/api"
  branch: v0.26.0
  remote_api_directory: pkg/operators
  local_api_directory: schemes/olm/operators
  excludes:
    - "*_test.go"
  replace_imports:
    - old: '"github.com/operator-framework/api/pkg/operators/v1"'
      new: '"github.com/rh-ecosystem-edge/eco-goinfra/pkg/schemes/olm/operators/v1"'
    - old: '"github.com/operator-framework/api/pkg/operators/v1alpha1"'
      new: '"github.com/rh-ecosystem-edge/eco-goinfra/pkg/schemes/olm/operators/v1alpha1"'
    - old: '"github.com/operator-framework/api/pkg/operators/v1alpha2"'
      new: '"github.com/rh-ecosystem-edge/eco-goinfra/pkg/schemes/olm/operators/v1alpha2"'
    - old: '"github.com/operator-framework/api/pkg/operators/install"'
      new: '"github.com/rh-ecosystem-edge/eco-goinfra/pkg/schemes/olm/operators/install"'
    - old: '"github.com/operator-framework/api/pkg/lib/version"'
      new: '"github.com/rh-ecosystem-edge/eco-goinfra/pkg/schemes/olm/version"'
    - old: '"github.com/operator-framework/api/pkg/operators"'
      new: '"github.com/rh-ecosystem-edge/eco-goinfra/pkg/schemes/olm/operators"'

- name: olm-version
  sync: true
  repo_link: "https://github.com/operator-framework/api"
  branch: v0.26.0
  remote_api_directory: pkg/lib/version
  local_api_directory: schemes/olm/version
  excludes:
    - "*_test.go"

- name: olm-package-server-operator
  sync: true
  repo_link: "https://github.com/operator-framework/operator-lifecycle-manager"
  branch: v0.26.0
  remote_api_directory: pkg/package-server/apis/operators
  local_api_directory: schemes/olm/package-server/operators
  excludes:
    - "*_test.go"
    - "packagemanifest.go"
  replace_imports:
    - old: '"github.com/operator-framework/api/pkg/operators/v1alpha1"'
      new: '"github.com/rh-ecosystem-edge/eco-goinfra/pkg/schemes/olm/operators/v1alpha1"'
    - old: '"github.com/operator-framework/operator-registry/pkg/registry"'
      new: '"github.com/rh-ecosystem-edge/eco-goinfra/pkg/schemes/olm/registry"'
    - old: '"github.com/operator-framework/api/pkg/lib/version"'
      new: '"github.com/rh-ecosystem-edge/eco-goinfra/pkg/schemes/olm/version"'
    - old: '"github.com/operator-framework/api/pkg/operators"'
      new: '"github.com/rh-ecosystem-edge/eco-goinfra/pkg/schemes/olm/operators"'
    - old: '"github.com/operator-framework/operator-lifecycle-manager/pkg/package-server/apis/operators"'
      new: '"github.com/rh-ecosystem-edge/eco-goinfra/pkg/schemes/olm/package-server/operators"'
    - old: '"github.com/operator-framework/operator-lifecycle-manager/pkg/package-server/apis/operators/v1"'
      new: '"github.com/rh-ecosystem-edge/eco-goinfra/pkg/schemes/olm/package-server/operators/v1"'
...