//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	configv1 "github.com/openshift/api/config/v1"
	hivev1 "github.com/openshift-kni/eco-goinfra/pkg/schemes/imagebasedinstall/hive/api/v1"
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalHostReference) DeepCopyInto(out *BareMetalHostReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalHostReference.
func (in *BareMetalHostReference) DeepCopy() *BareMetalHostReference {
	if in == nil {
		return nil
	}
	out := new(BareMetalHostReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageClusterInstall) DeepCopyInto(out *ImageClusterInstall) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageClusterInstall.
func (in *ImageClusterInstall) DeepCopy() *ImageClusterInstall {
	if in == nil {
		return nil
	}
	out := new(ImageClusterInstall)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImageClusterInstall) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageClusterInstallList) DeepCopyInto(out *ImageClusterInstallList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ImageClusterInstall, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageClusterInstallList.
func (in *ImageClusterInstallList) DeepCopy() *ImageClusterInstallList {
	if in == nil {
		return nil
	}
	out := new(ImageClusterInstallList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImageClusterInstallList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageClusterInstallSpec) DeepCopyInto(out *ImageClusterInstallSpec) {
	*out = *in
	if in.ClusterDeploymentRef != nil {
		in, out := &in.ClusterDeploymentRef, &out.ClusterDeploymentRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	out.ImageSetRef = in.ImageSetRef
	if in.ClusterMetadata != nil {
		in, out := &in.ClusterMetadata, &out.ClusterMetadata
		*out = new(hivev1.ClusterMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageDigestSources != nil {
		in, out := &in.ImageDigestSources, &out.ImageDigestSources
		*out = make([]configv1.ImageDigestMirrors, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CABundleRef != nil {
		in, out := &in.CABundleRef, &out.CABundleRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.ExtraManifestsRefs != nil {
		in, out := &in.ExtraManifestsRefs, &out.ExtraManifestsRefs
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.BareMetalHostRef != nil {
		in, out := &in.BareMetalHostRef, &out.BareMetalHostRef
		*out = new(BareMetalHostReference)
		**out = **in
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(Proxy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageClusterInstallSpec.
func (in *ImageClusterInstallSpec) DeepCopy() *ImageClusterInstallSpec {
	if in == nil {
		return nil
	}
	out := new(ImageClusterInstallSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageClusterInstallStatus) DeepCopyInto(out *ImageClusterInstallStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]hivev1.ClusterInstallCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BareMetalHostRef != nil {
		in, out := &in.BareMetalHostRef, &out.BareMetalHostRef
		*out = new(BareMetalHostReference)
		**out = **in
	}
	in.BootTime.DeepCopyInto(&out.BootTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageClusterInstallStatus.
func (in *ImageClusterInstallStatus) DeepCopy() *ImageClusterInstallStatus {
	if in == nil {
		return nil
	}
	out := new(ImageClusterInstallStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Proxy) DeepCopyInto(out *Proxy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Proxy.
func (in *Proxy) DeepCopy() *Proxy {
	if in == nil {
		return nil
	}
	out := new(Proxy)
	in.DeepCopyInto(out)
	return out
}
