name: Integration Testing

on:
  workflow_dispatch:
  # Triggers the workflow every day
  schedule:
    - cron: "0 0 * * *"
  # For the POC only, remove the pull_request trigger before merging
  pull_request:
    branches:
      - main

jobs:
  integration-k8s:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]
    env:
      SHELL: /bin/bash
      KUBECONFIG: '/home/runner/.kube/config'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Setup cluster (k8s)
        uses: palmsoftware/quick-k8s@v0.0.21

      - name: Run integration tests
        run: make integration-test

  integration-ocp:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    env:
      SHELL: /bin/bash
      KUBECONFIG: '/home/runner/.kube/config'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Setup cluster (ocp)
        uses: palmsoftware/quick-ocp@v0.0.5
        with:
          ocpPullSecret: ${{ secrets.OCP_PULL_SECRET }}
          bundleCache: true

      - name: Run integration tests
        run: make integration-test
