name: Test Incoming Changes

on:
  workflow_call:

  workflow_dispatch:

  push:

  pull_request:
    branches:
      - main
      - 'release-\d.\d\d'

jobs:
  lint:
    runs-on: ubuntu-22.04
    env:
      SHELL: /bin/bash

    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6

      - uses: actions/checkout@v4

      - name: Run lint
        run: make lint

  test:
    runs-on: ubuntu-22.04
    env:
      SHELL: /bin/bash

    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6

      - uses: actions/checkout@v4

      - name: Run unit tests
        run: make test

      - name: Generate test coverage
        run: go test ./pkg/... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: Check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          # Configure action using config file (option 1)
          config: ./.testcoverage.yml
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
          git-branch: badges
