name: Makefile CI

on:
  workflow_dispatch:

  push:

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      SHELL: /bin/bash

    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.6

      - uses: actions/checkout@v3

      - name: Run lint
        run: make lint
